version: '3'

networks:
  p-network:

services:
  # prometheus node
  prometheus:
    image: prom/prometheus
    volumes:
      - ./configs:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/docker.yml'
    ports:
      - 9090:9090
    networks:
      - p-network
    restart: always

  # ping/pong application server
  webserver:
    build:
      context: ./webserver
    ports:
      - 8090:8090
    networks:
      - p-network

  # visualize metrics with grafana
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
    networks:
      - p-network
    restart: always
